### ISSUE TITLE
Report Time when response received – submit time latency for tx

### ISSUE THREAD

**Issue by guoger** [Hyperledger-TWGC/tape#94]
following `key metrics` section in https://www.hyperledger.org/wp-content/uploads/2018/10/HL_Whitepaper_Metrics_PDFVersion.pdf, we would need to be able to report latency with `Tape`

**Comment by SamYuan1990** [comment]
Read Latency or Transaction Latency?

for my understanding, 
the Read Latency means the time diff between we send the envelope to orderer and the block event from peer grpc.
the Transaction Latency means the time diff between we send the envelope to orderer and the block confirmed at all peers configed in #43 ? 

Read Latency
Read Latency = Time when response received – submit time
Read latency is the time between when the read request is submitted and when the reply is
received.

Transaction Latency
Transaction Latency = (Confirmation time @ network threshold) – submit time
Transaction Latency is a network-wide view of the amount of time taken for a transaction’s
effect to be usable across the network. The measurement includes the time from the point
that it is submitted to the point that the result is widely available in the network. This includes
the propagation time and any settling time due to the consensus mechanism in place.
To account for both of those factors and give the network-wide view, the delay should be
measured using all nodes in the SUT. Eyal et al provide a helpful definition for the amount of
time for a percentage of the network to commit the transaction1, which we have simplified
somewhat here. The latter part of this definition, the percentage of the network, is most
significant for consensus protocols like PoW. In such systems a threshold like 90% may
be desired, whereas in a non-probabilistic protocol like PBFT 100% is the only meaningful
threshold.
This metric is computed per transaction, but in most cases reports should provide various
statistics over all transactions like the average, high, low, and standard deviations.

**Comment by guoger** [comment]
I'd say we'll do `Transaction Latency` first. `Read Latency` comes after issue #56

**Comment by SamYuan1990** [comment]
update issue title, and btw, how we summarize/display for the latency?
one by one tx?
avg/max?

**Comment by dexhunter** [comment]
Hi just wonder if the `submit time` in transaction latency equals the start of broadcasting?

**Comment by SamYuan1990** [comment]
#262, how about we create two matrix and integrated with prometheus to show up latency?

**Comment by SamYuan1990** [comment]
@guoger , @dexhunter , I just updated Tape with prometheus to report read latency and tx latency for p50, p90 and p99. please let me know if we are able to close this issue by prometheus supported. It looks like:
<img width="1724" alt="TapeLatency" src="https://user-images.githubusercontent.com/7820992/170855239-8f6223e4-4c73-47bb-aa74-6d75503605dd.png">
